### ISSUE TITLE
Browserify Compatible version pretty please

### ISSUE THREAD

**Issue by kristoferjoseph** [embedly/embedly-node#14]
First off, thanks for all of the hard work. Embedly is a really great product.

Is there any way you could find it in your heart to make this node version browserify compatible?

It currently has a dependency that uses `content = fs.readFileSync(file, 'ascii')` which causes the browser to fall all over itself.

Thanks whatever the answer is.

**Comment by dokipen** [comment]
Should be fixed now if you avoid winston.
