### ISSUE TITLE
Update superagent dependency

### ISSUE THREAD

**Issue by pdehaan** [embedly/embedly-node#15]
### Steps to reproduce
```sh
$ git clone https://github.com/embedly/embedly-node.git .
pdehaan:embedly-node pdehaan$ npm i && npm shrinkwrap --dev
wrote npm-shrinkwrap.json

$ nsp audit-shrinkwrap
Name  Installed  Patched  Vulnerable Dependency
qs      0.5.2     >= 1.x  embedly > superagent

$ npm outdated --depth 0
Package     Current  Wanted  Latest  Location
sprintf       0.1.1   0.1.1   0.1.5  sprintf
mocha         1.8.2   1.8.2   2.1.0  mocha
should        1.2.2   1.2.2   4.6.3  should
winston       0.6.2   0.6.2   0.9.0  winston
superagent   0.13.0  0.13.0  0.21.0  superagent
```

It looks like there are two known issues w/ the **qs** module which is used in older versions of **superagent**:
1. [**qs** Denial-of-Service Extended Event Loop Blocking](https://nodesecurity.io/advisories/qs_dos_extended_event_loop_blocking)
2. [**qs** Denial-of-Service Memory Exhaustion](https://nodesecurity.io/advisories/qs_dos_memory_exhaustion)

It looks like updating to **superagent@0.21.0** locally fixes the **qs** warning.

**Comment by dokipen** [comment]
Fixed in 1a7b47c1391cd42761f571f2a86eb897c2171faa
Published as v1.0.3

Thanks for reporting.
