### ISSUE TITLE
Constructor shouldn't be asynchronous

### ISSUE THREAD

**Issue by micky2be** [embedly/embedly-node#17]
`new Embedly` shouldn't need to get a callback as an argument.
If you need to send an http request to initialize the API just make a method for that.

**Comment by dokipen** [comment]
Pardon my ignorance. Why?

**Comment by micky2be** [comment]
It is simply bad practice. 
Writing `new Class()` should return an instance. Not execute code, and even less being asynchronous. 

I invite you to read the following answer for more details:
http://stackoverflow.com/a/24686979

**Comment by dokipen** [comment]
Alright. I really don't want to add another step, things should be as simple as possible, so I'll probably do some lazy init on first call. It might take me a little, pretty busy, but I will accept a patch that doesn't add another step to using our API.
