### ISSUE TITLE
Unhandled promise rejection TypeError: req.request is not a function(…)

### ISSUE THREAD

**Issue by leedium** [embedly/embedly-node#18]
Getting this issue running embedly in a Promise.

Seem like request is undefined in superagent.  Fixed it with the following

old:
`line 181 -     req.request().path += query;`

new:
`line 181-    req.query(params);`

**Comment by dokipen** [comment]
https://github.com/visionmedia/superagent/issues/128 <- are you sure this is no longer an issue?

**Comment by athomann** [comment]
I'm also getting this issue.

**Comment by dokipen** [comment]
Do you have some example code? I can't reproduce this.

**Comment by dokipen** [comment]
Fixed in latest superagent. Updated in v2.0.0. Careful, there are breaking changes. Check README.
