### ISSUE TITLE
`self` is not defined

### ISSUE THREAD

**Issue by chrisfosterelli** [embedly/embedly-node#21]
When upgrading to 2.0, the first API call fails with an error that `self` is not defined.
Looking to [the line that fails](https://github.com/embedly/embedly-node/blob/53068dfd69bcdcfc2faf0d7c81f7c7dcd9a91aee/index.js#L102), I don't see a definition of `var self = this` anywhere.

Was this missed? As far as I can tell this breaks 2.0 entirely.

**Comment by dokipen** [comment]
Please try 2.0.2, tests pass for me.

**Comment by dokipen** [comment]
ah, I see it. I don't have a test for this I guess, give me a few minutes

**Comment by dokipen** [comment]
I think the problem is that we no longer accept keyless API requests. It seems this code path only happens when there is no key.

**Comment by dokipen** [comment]
Removed ability to call API without a key.

**Comment by chrisfosterelli** [comment]
@dokipen Ah, yes it looks like when running tests I don't have that environment variable set. Thanks!
