### ISSUE TITLE
Error: socket hung up

### ISSUE THREAD

**Issue by robbiet480** [embedly/embedly-node#3]
Using this code:

```
var method = 'oembed'
var embedly = require("embedly")

var api = new embedly.Api({'key': 'XXXXXXXXXXXX', 'host': 'api.embed.ly', 'user_agent': 'Mozilla/5.0     (compatible; EmbedAllTheThings-Server/1.0; me@robbiet.us)', 'force':'true'})
api.oembed({urls: ['http://vimeo.com/18150336']}).on('complete', function(objs) {
console.log(objs[0])
}).on('error', function(e) {
console.error(e)
}).start()
```

It will randomly work and randomly won't, throwing the following error:

```
[Thu, 22 Dec 2011 00:54:44 GMT] DEBUG Calling http://api.embed.ly:80/1/oembed?urls=http%3A%2F%2Fvimeo.com%2F18150336&key=XXXXXX

node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
Error: socket hang up
    at createHangUpError (http.js:1092:15)
    at Socket.<anonymous> (http.js:1175:27)
    at Socket.emit (events.js:88:20)
    at Array.0 (net.js:300:10)
    at EventEmitter._tickCallback (node.js:192:40)
```

The code in ./bin/embedly_oembed.js doesn't work all the time either, throwing the same error. I have tried both the version in NPM and the latest from git (which appears to be the same)

**Comment by micky2be** [comment]
Sorry for digging this up but it's happening to me constantly when trying to extract urls from soundcloud

**Comment by micky2be** [comment]
Also happening with the url in the example by robblet480 (http://vimeo.com/18150336).
But working fine with URLs from Instagram, Youtube.

Amazon used to work but getting a `socket hang up` using those URLs too.

**Comment by dokipen** [comment]
what version of Node?

**Comment by dokipen** [comment]
Replace xxxxxxx with your actual key.
```
EMBEDLY_KEY=xxxxxxx bin/embedly_oembed.js https://soundcloud.com/devynfaucher/take-me-higher-demo -o force=true
```
I ran about 30 times without issue. Does it only happen certain times of day?

**Comment by micky2be** [comment]
Hmm, sorry guys. It was somewhere else in my code.
